import type { Config } from "tailwindcss";

export default {
  plugins: [],
  theme: {
    extend: {
      fontFamily: {
        cavet: ["Cavet", "cursive"],
        anton: ["Anton", "sans-serif"],
        titillium: ["TitilliumWeb", "sans-serif"],
      },
      margin: {
        xs: "2%",
        sm: "4%",
        md: "6%",
        lg: "8%",
        xl: "10%",
        "2xl": "12%",
        "3xl": "14%",
        "4xl": "16%",
        "5xl": "18%",
        "6xl": "20%",
      },
      padding: {
        xs: "2%",
        sm: "4%",
        md: "6%",
        lg: "8%",
        xl: "10%",
        "2xl": "12%",
        "3xl": "14%",
        "4xl": "16%",
        "5xl": "18%",
        "6xl": "20%",
      },
      backgroundImage: {
        logo: "url('/logo.png')",
        support: "url('/images/support.jpg')",
        discover: "url('/images/discover.jpg')",
        spiral: "url('/images/spiral-pattern.png')",
        "white-paper": "url('/images/white-paper.png')",
        newsletter: "url('/images/newsletter-bg.svg')",
        "banner-slide-back": "url('/images/home-slider-2-bg-back.jpg')",
        "banner-slide-front": "url('/images/home-slider-2-bg-front.png')",
        "home-slider-maison-1": "url('/images/home-slider-2-maison_1.png')",
      },
      scale: {
        "200": "2",
        "300": "3",
        "400": "4",
      },
      gridTemplateColumns: {
        "auto-fit-8": "repeat(auto-fit, minmax(8em, 1fr))",
        "auto-fit-10": "repeat(auto-fit, minmax(10em, 1fr))",
        "auto-fit-12": "repeat(auto-fit, minmax(12em, 1fr))",
        "auto-fit-14": "repeat(auto-fit, minmax(14em, 1fr))",
        "auto-fit-16": "repeat(auto-fit, minmax(16em, 1fr))",
        "auto-fit-18": "repeat(auto-fit, minmax(18em, 1fr))",
        "auto-fit-20": "repeat(auto-fit, minmax(20em, 1fr))",
        "auto-fit-22": "repeat(auto-fit, minmax(22em, 1fr))",

        "auto-fill-8": "repeat(auto-fill, minmax(8em, 1fr))",
        "auto-fill-10": "repeat(auto-fill, minmax(10em, 1fr))",
        "auto-fill-12": "repeat(auto-fill, minmax(12em, 1fr))",
        "auto-fill-14": "repeat(auto-fill, minmax(14em, 1fr))",
        "auto-fill-16": "repeat(auto-fill, minmax(16em, 1fr))",
        "auto-fill-18": "repeat(auto-fill, minmax(18em, 1fr))",
        "auto-fill-20": "repeat(auto-fill, minmax(20em, 1fr))",
        "auto-fill-22": "repeat(auto-fill, minmax(22em, 1fr))",
      },
    },
  },
  content: ["./src/**/**/*.{js,ts,jsx,tsx,mdx}"],
} satisfies Config;
